auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# not sure if this is necessary
# ingester:
#   max_chunk_age: 72h
#
# limits_config:
#   retention_period: 336h
#   reject_old_samples: false
#   reject_old_samples_max_age: 43800h

limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 90d
  max_query_length: 0h # Default: 721h

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
  - from: 2020-08-19
    store: cassandra
    schema: v11
    index:
      prefix: index_
      period: 90d # 168h
    chunks:
      prefix: chunk_
      period: 90d # 168h

storage_config:
  cassandra:
    addresses: 127.0.0.1
    auth: false
    keyspace: lokiindex
    replication_factor: 1 # just testing on a single host

ruler:
  alertmanager_url: http://localhost:9093

# on-prem is firewalled anyway
analytics:
 reporting_enabled: false
