server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

# https://gist.github.com/cspinetta/41db2cc7f03a5af49e1b1cfe68d1fea4

scrape_configs:
- job_name: onpremsystem
  pipeline_stages:
    - json:
        expressions:
          time: timestamp
          message: message
          thread_name: thread_name
          level: level
          trace_id: traceId
          span_id: spanId
          stack_trace: stack_trace
    - timestamp:
        source: time
        # format: RFC3339Nano
        format: 2006-01-02T15:04:05.000000
    - labels:
        level:
  static_configs:
  - targets:
      - localhost
    labels:
      job: onpremlogs
      __path__: /scratch/onpremsystemlogs/foo*.log
